=== mazecross/postgraduate/semi-structured data and web/testfiles/calc2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This is a simple format for excoding arithmetic 
     expressions on integers. The operations in question
     are +, -, and / The output is always a decimal. 
     
     This DTD was written by Bijan Parsia, Copyright 2010-2011
     all rights reserved. You may
     not use it or copy it except in the context of
     COMP60411 without written permission.
     
     This is also used in the SAXCalc assignment. -->
     
<!-- Notice the level of commenting! -->

<!-- I used parameter entities in order to simplify
     the DTD, as well as making it both more readable
     and more modular. If I want to add a decimal type
     or an additional operation (such as division), I 
     need only touch this declaration. -->
<!ENTITY % expr "(plus | times | dividedBy | minus | int )">

<!-- This is my intended root element. -->
<!ELEMENT expression %expr;>

<!ELEMENT times (%expr;, (%expr;)+)>
<!ELEMENT plus (%expr;, (%expr;)+)>

<!-- Note that minus and divided by are *binary* operations -->
<!ELEMENT minus (%expr;, %expr;)>
<!ELEMENT dividedBy (%expr;, %expr;)>

<!-- Ints are empty elements. I use an attribute
     for the value. There's no special reason
     for this other than I can put an *inadequeate*
     type constraint on it. It's not even shorter, viz.:
        <int>576</int>
        <int value="572"/>-->
<!ELEMENT int EMPTY>
<!ATTLIST int value NMTOKEN #REQUIRED>

=== mazecross/postgraduate/semi-structured data and web/testfiles/bjp-test2_6.5.xml
<!DOCTYPE expression SYSTEM "calc2.dtd">
<expression>
    <!-- This expression evaluates to 6.5.
         It was one of the examples.
         10/(4-24)+7-->
    <plus>
        <dividedBy>
            <int value="10"/>
            <minus>
                <int value="4"/>
                <int value="24"/>
            </minus>
        </dividedBy>
        <int value="7"/>
    </plus>
</expression>
